[[redirects]]
from = "/api/generate_image/"
to = "http://54.188.27.139:8080/generate_image/"
status = 200
force = true
conditions = {Method = ["POST"]}

[[redirects]]
from = "/*"
to = "/index.html"
status = 200